name: iOS Build
on:
  workflow_dispatch:
jobs:
  iOS:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v4
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-ios
          path: |
            .haxelib/
            export/release/ios/CodenameEngine/haxe/
          restore-keys: |
            cache-build-ios

      - name: Install Libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s
          haxelib remove lime
          haxelib git lime https://github.com/moxie-coder/lime-8.2.2 --quiet
          haxelib run lime rebuild hxcpp

      - name: Compile
        run: haxelib run lime build ios -clean -nosign
      - name: Clearing already existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-ios") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Making ipa file
        run: |
          brew install ldid
          cd export/release/ios/build/Release-iphoneos/CodenameEngine.app
          ldid -S../../../CodenameEngine/CodenameEngine.entitlements CodenameEngine
          cd ..
          mkdir Payload
          mv CodenameEngine.app Payload
          zip -r CodenameEngine.ipa Payload
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: Codename Engine iOS
          path: export/release/ios/build/Release-iphoneos/*.ipa
      - name: Uploading new cache
        uses: actions/cache@v4
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-ios
          path: |
            .haxelib/
            export/release/ios/CodenameEngine/haxe/
          restore-keys: |
            cache-build-ios
